const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getData: () => ipcRenderer.invoke('get-data'),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  getUpdateStatus: () => ipcRenderer.invoke('get-update-status'),
  setAutomaticUpdates: (enabled) => ipcRenderer.invoke('set-automatic-updates', enabled),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  downloadUpdate: () => ipcRenderer.invoke('download-update'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  onUpdateStatus: (callback) => ipcRenderer.on('update-status', (_event, status) => callback(status)),
  updateSites: (sites) => ipcRenderer.invoke('update-sites', sites),
  updateAllowedSites: (sites) => ipcRenderer.invoke('update-allowed-sites', sites),
  updateApps: (apps) => ipcRenderer.invoke('update-apps', apps),
  startLock: (minutes) => ipcRenderer.invoke('start-lock', { minutes }),
  getLockStatus: () => ipcRenderer.invoke('get-lock-status'),
  getSchedules: () => ipcRenderer.invoke('get-schedules'),
  saveSchedule: (schedule) => ipcRenderer.invoke('save-schedule', schedule),
  deleteSchedule: (id) => ipcRenderer.invoke('delete-schedule', id),
  temporaryUnblock: (minutes, sites, apps) => ipcRenderer.invoke('temporary-unblock', { minutes, sites, apps }),
  clearTemporaryUnblock: () => ipcRenderer.invoke('clear-temporary-unblock'),
  remoteCommand: (host, password, command, payload, role) => ipcRenderer.invoke('remote-command', { host, password, command, payload, role }),
  discoverNetwork: () => ipcRenderer.invoke('discover-network'),
  networkSpeedTest: () => ipcRenderer.invoke('network-speed-test'),
  onNetworkSpeedStage: (callback) => ipcRenderer.on('network-speed-stage', (_event, stage) => callback(stage)),
  getNetworkGroups: () => ipcRenderer.invoke('get-network-groups'),
  setAgentPassword: (password) => ipcRenderer.invoke('set-agent-password', password),
  getAgentSecurityStatus: () => ipcRenderer.invoke('get-agent-security-status'),
  updateAllowedControllers: (ips) => ipcRenderer.invoke('update-allowed-controllers', ips),
  getControllerIdentity: () => ipcRenderer.invoke('get-controller-identity'),
  generatePairingCode: () => ipcRenderer.invoke('generate-pairing-code'),
  getPairingStatus: () => ipcRenderer.invoke('get-pairing-status'),
  cancelPairing: () => ipcRenderer.invoke('cancel-pairing'),
  enrollController: (host, code, label, role) => ipcRenderer.invoke('enroll-controller', { host, code, label, role }),
  remoteCommandSigned: (host, command, payload) => ipcRenderer.invoke('remote-command-signed', { host, command, payload }),
  getEnrolledControllers: () => ipcRenderer.invoke('get-enrolled-controllers'),
  removeEnrolledController: (id) => ipcRenderer.invoke('remove-enrolled-controller', id),
  setAllowLegacyPassword: (allowed) => ipcRenderer.invoke('set-allow-legacy-password', allowed),
  saveNetworkGroup: (group) => ipcRenderer.invoke('save-network-group', group),
  deleteNetworkGroup: (groupId) => ipcRenderer.invoke('delete-network-group', groupId),
  onNetworkGroupsUpdated: (callback) => ipcRenderer.on('network-groups-updated', () => callback())
});
